[package]
name = "the-celvestian-creations/cannon-project"
version = "0.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
# Evaera's Libraries
Promise = "evaera/promise@4.0.0"
Matter = "hackpro8000/matter@0.9.0-beta.0"

# Roblox Official Libraries
Rodux = "roblox/rodux@3.0.0"

# Sleitnick's Libraries
Comm = "sleitnick/comm@1.0.1"
Loader = "sleitnick/loader@2.0.0"
Net = "sleitnick/net@0.2.0"
Signal = "sleitnick/signal@2.0.3"
Sequent = "sleitnick/sequent@0.1.0"
Trove = "sleitnick/trove@1.5.0"

# Other Libraries
SPR = "blackjackiee/spr@1.1.3"

[server-dependencies]
ProfileStore = "lm-loleris/profilestore@1.0.3"