[package]
name = "hackpro8000/matter"
description = "Matter ECS Lib but I fixed the wally.toml file"
version = "0.9.0-beta.0"
license = "MIT"
authors = [
    "Eryn L. K.",
    "Lucas Gangstad <lucas@lasttalon.dev>",
    "Ukendio <ukendio@gmail.com>",
]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = [
    "example",
    "docs",
    "Packages",
    ".moonwave",
    "build",
    "pages",
    "tests",
    "benchmarks",
    "AttackOfTheKillerRoombas.rbxl",
    "AttackOfTheKillerRoombas.rbxl.lock",
    "matter.rbxl",
    "matter.rbxm",
    "roblox.toml",
]
